### ISSUE TITLE
Add the ability to disable an admin or volunteer

### ISSUE THREAD

**Issue by Dafondo** [unc-cs-sg/carolinacupboard-inventory#15]
**Context:**
1. The `Transactions` table has a foreign key from the `Users` table for `volunteer_id` to record which volunteer checked out an item. In order to delete users from the `Users` table, all transactions with that `volunteer_id` must be deleted from the `Transactions` table.
1. It is not possible to delete a single entry from the `Transactions` table through the client. An admin may only clear the entire `Transactions` table.
1. Sometimes, an admin may need to delete a user urgently, and it may be unfeasible or inconvenient to clear the `Transactions` table.

**Consider:**
1. Adding a `disabled` role to the `Users` schema to indicate a user that is no longer and admin or volunteer.
1. Allow an admin to change a user's role to `disabled`, but not to create a new user with the role `disabled`.

**Done:**
1. An admin can remove an admin or volunteers permissions without needing to first clear the `Transactions` table.

**Comment by ByrdOfAFeather** [comment]
[Branch for review ](https://github.com/unc-cs-sg/carolinacupboard-inventory/tree/disable_admin_volunt)

**Comment by Dafondo** [comment]
Looks good! @ByrdOfAFeather, you can open a new PR. We'll merge it in after we finish an ongoing data transfer project with Carolina Cupboard.
