### ISSUE TITLE
Improve backup and deletion workflow

### ISSUE THREAD

**Issue by Dafondo** [unc-cs-sg/carolinacupboard-inventory#7]
**Context**
1. Currently, an admin may download CSVs and delete tables for the `Items` and `Transactions` tables with no restrictions. It is possible for an admin to delete tables without downloading a backup for them first.
1. The `Transactions` table has a foreign key constraint on the `Items` table because each transaction references a specific item. Currently, it is possible for an admin to try deleting the `Items` table before deleting the `Transactions` table.

**Consider**
1. Creating a front-end workflow that requires an admin to download CSVs of a table before deleting it/
1. Creating a front-end workflow that requires an admin to delete the `Transactions` table before deleting the `Items` table.
1. Adding back-end logic to check and report foreign key constraints that prevent table deletion.

**Done**
1. An admin must backup tables before deleting them.
1. An admin must delete the `Transactions` table before deleting the `Items` table.

**Comment by ByrdOfAFeather** [comment]
Pushed to: 
https://github.com/unc-cs-sg/carolinacupboard-inventory/tree/backup-deletion-wrkflw

a fix that should take care of error checking.

**Comment by Dafondo** [comment]
Closing this issue for now. Carolina Cupboard volunteers have no complaints about the current workflow and any more improvements seem like too much effort at the moment.
