### ISSUE TITLE
CSV import confirmation

### ISSUE THREAD

**Issue by Dafondo** [unc-cs-sg/carolinacupboard-inventory#9]
**Context**
1. Currently, when an admin imports a CSV file, the page is re-rendered with no confirmation of their action. This may be confusing because they must navigate to another page to confirm that the import was successful.

**Consider**
1. Rendering a new page and/or a status message (success or error) when an admin imports a CSV file.

**Done**
1. When an admin imports a CSV file, they know immediately whether the operation was successful or not.

**Comment by jackgoldsmith4** [comment]
Feature added in #23
